#!/bin/bash

module load afni19.3.03

# this script runs the ISC-SME analyses


# define path
path="/storage/shared/research/cinn/2018/MAGMOT"

ana_path="$path"/derivatives/magictrickwatching/analyses/

# execute ISC_SME
source "$ana_path"ISC_SME_aboveAvgConf/run_3dISC_aboveAvgConf > "$ana_path"ISC_SME_aboveAvgConf/output_3dISC_aboveAvgConf.txt 
source "$ana_path"ISC_SME_highConf/run_3dISC_highConf > "$ana_path"ISC_SME_highConf/output_3dISC_highConf.txt 
source "$ana_path"ISC_SME_allConf/run_3dISC_allConf > "$ana_path"ISC_SME_allConf/output_3dISC_allConf.txt 


