#!/bin/bash

################################################################################
# converting FreeSurfer to AFNI to create masks for pre-processing
################################################################################


# please note that this script needs to be run locally as the virtual machines cause issues
# this script has to be run after the FS recon-all command

# load necessary modules
module load freesurfer6.0.0
module load afni19.3.03

# define DIR
DIR=/Users/stefaniemeliss/cinn/2018/MAGMOT
DIR=/storage/shared/research/cinn/2018/MAGMOT

# change directory to the raw NIFI files
cd $DIR/MAGMOT_BIDS/

# define subjects based on folder names in the BIDS directory
subjects=($(ls -d sub*))
#subjects=(sub-control001 sub-control002 sub-control003 sub-experimental004 sub-experimental005 sub-experimental006)
#subjects=(sub-experimental005)


# for each subject in the subjects array
for subject in "${subjects[@]}"; do

	echo $subject

	# create anat folder in derivatives
	anat_deriv=$DIR/derivatives/"${subject}"/anat
	mkdir $anat_deriv

	# cd into subject folder
	cd $DIR/derivatives/FreeSurfer/"${subject}"/

	# use SUMA to convert
	echo START WITH SUMA CONVERSION
	@SUMA_Make_Spec_FS -sid ${subject} -NIFTI

	# cd into SUMA folder
	cd $DIR/derivatives/FreeSurfer/"${subject}"/SUMA/

	# copy discrete segmentation files to derivatives/${subject}/anat folder
	# note: REN = renumbered
	# for Desikan-Killiany, see https://afni.nimh.nih.gov/pub/dist/src/scripts_install/afni_fs_aparc+aseg_2000.txt 
	# for Destrieux, see https://afni.nimh.nih.gov/pub/dist/src/scripts_install/afni_fs_aparc+aseg_2009.txt
	3dcopy aparc+aseg_REN_all.nii.gz $anat_deriv/"${subject}"_space-orig_desc-Desikan-Killiany_dseg.nii.gz
	3dcopy aparc.a2009s+aseg_REN_all.nii.gz $anat_deriv/"${subject}"_space-orig_desc-Destrieux_dseg.nii.gz

	# create masks
	echo CREATE THE WM AND VENTRICLE MASK

	# select ventricles from FS output aparc+aseg.nii (numbering corresponds to FS)
	3dcalc -a aparc+aseg.nii -datum byte \
	-prefix FSmask_vent.nii -expr 'amongst(a,4,43)' 
	# 4	Left-Lateral-Ventricle
	# 43	Right-Lateral-Ventricle

	# select the WM maps from FS output aparc+aseg.nii (numbering corresponds to FS)
	3dcalc -a aparc+aseg.nii -datum byte \
	-prefix FSmask_WM.nii -expr 'amongst(a,2,7,41,46,251,252,253,254,255)'
	# 7		Left-Cerebellum-White-Matter
	# 41	Right-Cerebral-White-Matter
	# 46	Right-Cerebellum-White-Matter
	# 251	CC_Posterior
	# 252	CC_Mid_Posterior
	# 253	CC_Central
	# 254	CC_Mid_Anterior
	# 255	CC_Anterior
	# note: Chen et al. 2016 also included # 16	Brain-Stem, but this is omitted here


	# select GM mask
	3dmask_tool -input aparc+aseg_REN_gm.nii.gz -prefix FSmask_GM.nii
	#3dmask_tool -input aparc+aseg_REN_wmat.nii.gz -prefix WM_mask.nii
	#3dmask_tool -input aparc+aseg_REN_vent.nii.gz -prefix VENT_mask.nii

done

