#!/bin/bash

# please note that this script needs to be run locally as the virtual machines cause issues
# this script has to be run after the FS recon-all command

# load necessary modules
module load freesurfer6.0.0
module load afni19.2.07
module load afni19

# define DIR
DIR=/Users/stefaniemeliss/cinn/2018/MAGMOT
DIR=/storage/shared/research/cinn/2018/MAGMOT

# change directory to the raw NIFI files
cd $DIR/MAGMOT_BIDS/

# define subjects based on folder names in the BIDS directory
subjects=($(ls -d sub*))
#subjects=(sub-control001 sub-control002 sub-control003 sub-experimental004 sub-experimental005 sub-experimental006)
subjects=(sub-experimental005)


# for each subject in the subjects array
for subject in "${subjects[@]}"; do

echo $subject

# cd into subject folder
cd $DIR/derivatives/FreeSurfer/"${subject}"/

# use SUMA to convert
echo START WITH SUMA CONVERSION
@SUMA_Make_Spec_FS -sid ${subject} -NIFTI

# cd into SUMA folder
cd $DIR/derivatives/FreeSurfer/"${subject}"/SUMA/

# select the ventricle maps from FS output
echo CREATE THE WM AND VENTRICLE MASK
3dcalc -a aparc+aseg.nii -datum byte \
-prefix FSmask_vent.nii -expr 'amongst(a,4,43)' # this selects left and right vent: numbers assigned by FS automated labeling procedure 

# select the WM maps from FS output
3dcalc -a aparc+aseg.nii -datum byte \
-prefix FSmask_WM.nii -expr 'amongst(a,2,7,16,41,46,251,252,253,254,255)' # this selects left and right cerebral and cerebellum WM, brain stem, and Corpus Callosum

# select the GM maps from FS output
#3dcalc -a aparc+aseg.nii -datum byte \
#-prefix FSmask_GM.nii -expr 'amongst(a,3,42,8,47,163,164)' # this selects left and right cerebral cortex, cerebellum cortex and subcortical GM
3dcalc -a aparc+aseg.nii -datum byte \
-prefix FSmask_GM.nii -expr 'amongst(a,3,42)' # this selects left and right cerebral cortex, cerebellum cortex and subcortical GM

	
done

