#!/bin/bash

module load afni19.3.03

# this script runs the ISC-RSA analyses


# define path
path="/storage/shared/research/cinn/2018/MAGMOT"
ISC_path="$path"/derivatives/magictrickwatching/ISC/
ana_path="$path"/derivatives/magictrickwatching/analyses/ISC_magictrickwatching/
script_path="$path"/derivatives/magictrickwatching/analyses/scripts/ISC/
mkdir $ana_path


# change directory to ISC folder
cd $ISC_path

# get all files in an array
input=*magictrickwatching_z.nii.gz

# create array containing all ISC for each pair
array=(`find $ISC_path -name "${input}"`)
length_array=${#array[@]}
echo $length_array

# change directory to analyses folder
cd $ana_path

# copy files
for (( f=0; f<${length_array}; f++));
    do

	# define file_id
    file_id=${array[$f]}
	echo $file_id
	# copy file
	cp $file_id .

done

# Set directory
cd $ana_path


# define ROI masks
masks=(pHPC aHPC HPC VTA Caudate NAcc GM)
masks=(V1 V2 A1 Caudate_func)

#masks=(GruberVTA GruberNAcc GruberHPC) # redo with new ROI masks

num_masks=${#masks[@]}



# loop over masks to create a 3dISC for each mask
for (( m=0; m<${num_masks}; m++));
	
	do
	# define variables
	cov=${covariates[$v]}
	mask=${masks[$m]}
	# run the model
	source "$script_path"3dISC_magictrickwatching_"$mask" > "$script_path"output_3dISC_magictrickwatching_"$mask".txt

done



# execute ISC_magictrickwatchings
#source "$ana_path"run_3dISC_magictrickwatching_uniqueCurAboveAvgConf > "$ana_path"output_3dISC_magictrickwatching_uniqueCurAboveAvgConf.txt
#source "$ana_path"run_3dISC_magictrickwatching_uniqueMemAboveAvgConf > "$ana_path"output_3dISC_magictrickwatching_uniqueMemAboveAvgConf.txt
#source "$ana_path"run_3dISC_magictrickwatching_uniqueConfidence > "$ana_path"output_3dISC_magictrickwatching_uniqueConfidence.txt


