#!/bin/bash
source ~/.bashrc

# load modules
module load afni19.3.03
# load anaconda - this is necessary to have all python libraries available
module load anaconda3

#define path
path="/storage/shared/research/cinn/2018/MAGMOT"

# change directory to BIDS folder
cd "$path"/MAGMOT_BIDS/

# define subjects based on folder names in the BIDS directory
subjects=($(ls -d sub*))

# define which subjects should be excluded
subjects_excl=(sub-experimental000)

# exclude subjects: compare the elements of subjects_excl and subjects
# if they match, delete (i.e. unset) the element in subject 
for e in ${!subjects_excl[@]}; do 
	excl=${subjects_excl[$e]}
	for i in ${!subjects[@]}; do
	subj=${subjects[$i]}
		if [[ "$excl" == "$subj" ]]; then
			unset subjects[i]
			subjects=( "${subjects[@]}" )
		fi
	done
done

#subjects=(sub-control001 sub-control002 sub-control003 sub-experimental004 sub-experimental005 sub-experimental006) # script development
#subjects=(sub-control041) # script development


# for each subject in the subjects array
for subject in "${subjects[@]}"; do
	echo $subject

	# define all necessary directories
	fildirTASK=$path/derivatives/magictrickwatching/concat/$subject	
	fildirREST=$path/MAGMOT_BIDS/$subject/func
	fildirQC=$path/derivatives/pyfMRIqc/$subject	
	mkdir $fildirQC

	# copy task files
	cd $fildirTASK
	filesTASK=($(ls -d *magictrickwatching*concat.nii.gz))
	for fileTASK in "${filesTASK[@]}"; do
		searchstring="nii.gz"
		replacestring="nii"	
		fileTASK_new="${fileTASK/$searchstring/$replacestring}"	
		3dcopy $fildirTASK/$fileTASK $fildirQC/$fileTASK_new
	done	

	# copy rest files
	cd $fildirREST
	filesREST=($(ls -d *rest*.nii.gz))
	for fileREST in "${filesREST[@]}"; do
		searchstring="nii.gz"
		replacestring="nii"	
		fileREST_new="${fileREST/$searchstring/$replacestring}"	
		3dcopy $fildirREST/$fileREST $fildirQC/$fileREST_new
	done

	# create files array with nifti files
	cd $fildirQC
	files=($(ls -d sub*.nii*))

	# loop through the files that have been copied over
	for file in "${files[@]}"; do

		cd $fildirQC

		#########################
		### MOTION CORRECTION ###
		#########################

		# define file prefix for motion corrected files
		searchstring="sub"
		replacestring_3d="volreg_sub"	
		replacestring_1d="motion_sub"
		replacestring_plot="plot_sub"
		searchending=".nii"
		replaceending=""
		volreg_prefix="${file/$searchstring/$replacestring_3d}"	
		file_suffix="${file/$searchending/$replaceending}" 
		motionfile_prefix="${file_suffix/$searchstring/$replacestring_1d}".1D	
		plot_prefix="${file_suffix/$searchstring/$replacestring_plot}"

		# run motion correction
		3dvolreg -verbose -prefix $volreg_prefix -1Dfile $motionfile_prefix  $file 

		# look at the 1dplot
		1dplot -volreg -sepsc1 -png $plot_prefix $motionfile_prefix &


		##########################
		###### CREATE MASK  ######
		##########################

		# define file prefix for mask
		searchstring="sub"
		replacestring_mask="mask_sub"	
		mask_prefix="${file/$searchstring/$replacestring_mask}"	

		# use 3dAutomask to perform skull-stripping and masking on EPI data (default in pre-processing)
		3dAutomask -prefix $mask_prefix $file

		##########################
		###### RUN pyfMRIqc ######
		##########################

		# change directory to pyfMRIqc-master
		cd /storage/shared/research/cinn/2018/MAGMOT/software/pyfMRIqc-fix-rm

		# define input parameters
		func_nift_file=$fildirQC/"${file}"
		SNR_voxel_perc=25
		#mask_threshold=200
		motion_file=$fildirQC/"${motionfile_prefix}"
		mask_nift_file=$fildirQC/"${mask_prefix}"

		#python pyfMRIqc.py -n $func_nift_file -s $SNR_voxel_perc -m $motion_file -k $mask_nift_file
		python pyfMRIqc.py -n $func_nift_file -s $SNR_voxel_perc -m $motion_file -k $mask_nift_file

	done 

done






