#!/bin/bash
source ~/.bashrc

module load afni19

# define path
path="/storage/shared/research/cinn/2018/MAGMOT"

# go to directory with concat files
concat_root=$path"/derivatives/magictrickwatching/concat/"
cd $concat_root


# BOTH REMEMBERED FILES
input1=*bothRemembered*SME_afniproc.nii.gz

searchstring="afniproc.nii.gz"
replacestring="afniproc_bold.nii.gz"

array1=(`find . -name "${input1}"`)
length_array1=${#array1[@]}
echo $length_array1

for (( f=0; f<${length_array1}; f++));
    do

	# define file_id
    file_id1=${array1[$f]}

	# define tcat prefix
	tcat_prefix1="${file_id1/$searchstring/$replacestring}"

	if [ ! -f "$tcat_prefix1" ]; then
		echo $tcat_prefix1
		# after concatenation, header need to be overwritten
		3dTcat -prefix $tcat_prefix1 $file_id1
		# delete old file
		rm $file_id1

	fi

done



# BOTH FORGOTTEN FILES
input2=*bothForgotten*SME_afniproc.nii.gz

array2=(`find . -name "${input2}"`)
length_array2=${#array2[@]}
echo $length_array2

for (( f=0; f<${length_array2}; f++));
    do

	# define file_id
    file_id2=${array2[$f]}

	# define tcat prefix
	tcat_prefix2="${file_id2/$searchstring/$replacestring}"

	if [ ! -f "$tcat_prefix2" ]; then
		echo $tcat_prefix2
		# after concatenation, header need to be overwritten
		3dTcat -prefix $tcat_prefix2 $file_id2
		# delete old file
		rm $file_id2

	fi
done


#find . -name "*afniproc_ordered.nii" -print

# MAGICTRICK WATCHING FILES
input=*afniproc_ordered.nii.gz

# define file prefix tcat file
searchstring2="ordered.nii.gz"
replacestring2="ordered_bold.nii.gz"

array=(`find . -name "${input}"`)
length_array=${#array[@]}
echo $length_array

for (( f=0; f<${length_array}; f++));
    do

	# define file_id
    file_id=${array[$f]}

	# define tcat prefix
	tcat_prefix="${file_id/$searchstring2/$replacestring2}"

	if [ ! -f "$tcat_prefix" ]; then
		echo $tcat_prefix
		# after concatenation, header need to be overwritten
		3dTcat -prefix $tcat_prefix $file_id
		# delete old file
		rm $file_id
 
	fi

done
